CREATE TABLE IF NOT EXISTS study_records (
    id BIGSERIAL PRIMARY KEY,
    created_at TEXT NOT NULL,
    updated_at TEXT,
    problem TEXT NOT NULL,
    solution TEXT,
    goal TEXT,
    user_method TEXT,
    recommended TEXT,
    confidence TEXT,
    cues_json TEXT,
    missing_json TEXT,
    misconceptions_json TEXT,
    memo TEXT,
    problem_type TEXT,
    applicable_json TEXT,
    not_applicable_json TEXT,
    mistake_tags_json TEXT,
    extra_json TEXT,
    favorite INTEGER DEFAULT 0,
    difficulty TEXT,
    wrong_reasons_json TEXT,
    review_due_at TEXT,
    needs_review INTEGER DEFAULT 0
);
